# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: kiookp
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_chess: yes
          plugin_chess_animation: {
  "size": 40,
  "delay": 3,
  "duration": 0.6
}

          plugin_chess_platform: lichess.org
          plugin_chess_user: .user.login
